vaccine_words = [
    "vaccine",
    "side-effects",
    "alternatives",
    "contamination",
    "autism",
    "immune system",
    "infant",
    "safety",
    "efficacy",
    "clinical trials",
    "approval process",
    "children",
    "toxin",
    "toxic"
]

cam_words = [
    "immunization",
    "holistic",
    "herbal",
    "homeopathy",
    "naturopathy",
    "ayurveda",
    "aromatherapy",
    "spiritual",
    "osteopathy",
    "anthroposophic",
    "anthroposophy"
    "non-toxic",
    "ingredients",
    "acupuncture",
    "chiropractic",
    "reiki",
    "hypnotherapy",
    "yoga therapy",
    "meditation",
    "naturopathic",
    "naturopath",
    "herbalist",
    "acupuncturist",
    "chiropractor",
    "nutritionist",
    "energy-healer",
    "aromatherapist"
]